name: Show Commit Info

on:
  push:
    branches:
      - '**'

jobs:
  show-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Commit Info
        run: |
          echo "$(git log -1 --pretty=format:'ğŸ‘¤ %an%nğŸ”¢ %h%nğŸ“ %s')"
